#include "tlpp-core.th"

namespace Gworks.Templates.APITrace.Metadata

User Function MetadataConfigService()

    Local cError as character
    Local lResult as logical

    BEGIN SEQUENCE

        if!( lResult := U_HeaderSchema( @cError ) )
            BREAK
        endif

    END SEQUENCE

    if( !lResult )

        oMessage_:SetProperty( "error_state", .T. )
        oMessage_:SetProperty( "error_message", "Falha ao validar/criar metadados!" )
        oMessage_:SetProperty( "error_suggestion", "Favor contactar o suporte técnico." )
        oMessage_:SetProperty( "error_title", "Falha!" )
        oMessage_:SetProperty( "error_style", "HELP" )
        oMessage_:SetProperty( "error_details", cError )
        oMessage_:SetProperty( "log_state", "ERROR")
        oMessage_:Display()

    endif

Return lResult
